version: 2.1

jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: 'Update NPM'
          command: sudo npm install -g npm@6.13.4
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Compile contracts
          command: npm run compile
      - run:
          name: Run tests
          command: npm run test

workflows:
  main:
    jobs:
      - build_and_test
